apiVersion: v1
kind: Service
metadata:
    name: peitho-service-lb
spec:
    type: LoadBalancer
    ports:
        - name: "8080"
          port: 8080
          targetPort: 80
        - name: "8081"
          port: 8081
          targetPort: 443
    selector:
        app: olympus-frontend
