apiVersion: v1
kind: Service
metadata:
  labels:
    run: athena-db
  name: athena-db-service
spec:
  ports:
    - name: "1433"
      port: 1433
      targetPort: 1433
  selector:
    db: athena-db
status:
  loadBalancer: {}
